### ISSUE TITLE
Add SPEEDY climate model

### ISSUE THREAD

**Issue by tkoskela** [Team-RADDISH/ParticleDA.jl#199]
Within the extension of the project, we are adding a new model, [speedy](https://github.com/samhatfield/letkf-speedy/tree/master/model)

## Workflow
- Call speedy bash script that
  - sets up inputs
  - executes Fortran executable
- Read outputs from Fortran binary files and populate `model_data`

## Tasks
- [x] write new `update_particle_dynamics!` function
- [ ] write IO function(s) for speedy output files

**Comment by tkoskela** [comment]
Issues with 2D vs 3D
- Gaussian random field generator: Looks like it will work but needs testing
- get_mean_and_var: Easy to generalise because we don't use the dimension. We can assert that `size(statistics) == size(particles) - 1`
- copy_states: Needs to be generalised to use the "last" dimension. [This should do it](https://github.com/ChrisRackauckas/EllipsisNotation.jl)
- State vectors: Are defined in the model

**Comment by DanGiles** [comment]
I am having difficulty with writing to a Fortran file that SPEEDY will accept. Please see my current [write_fortran](https://github.com/DanGiles/ParticleDA.jl/blob/dg/speedy/speedy/model/model.jl) (line 520) function which relies on FortranFiles.jl. The files it creates can be read in correctly using our previous reading function. Unfortunately, SPEEDY will not accept them and they cause the SPEEDY model to crash - with no useful outputs appearing. 

The write_fortran function should replicate the behaviour of the following SPEEDY [write_grd4](https://github.com/samhatfield/letkf-speedy/blob/master/common/common_speedy.f90) function (line 197). 

Perhaps this behaviour is due to the `unformatted` argument (padding the records before and after) in write_grd4 currently not being replicated in the Julia function. Your help would be much appreciated!

**Comment by giordano** [comment]
Could you please show exactly what you've tried?  For example, I tried to generate a file with your `write_fortran` function like this:
```julia
using .Model: write_fortran

nlon = 2
nlat = 
nlev = 2
filename = tempname()
nij0 = nlon*nlat
iolen = 4
T = Float32
dataset = rand(T, nlon, nlat, nlev, 6)
write_fortran(filename, nlon, nlat, nlev, dataset)
```
and then I can read it back, always using the Julia package `FortranFiles`, with
```julia
f = FortranFile(filename, "r", convert="big-endian", access="direct", recl=(nij0*iolen))
read(f, T; rec=1)
```
Are you doing something similar to write the file?  How are you reading it from your Fortran program?  Anything simple I can try locally to debug it?

**Comment by DanGiles** [comment]
I have tested the reading and writing functions by running the following:
```Julia
nlon = 96

nlat = 48

nlev = 8

T = Float64

n3d = 4

n2d = 2
# Read in the SPEEDY initial state file
(v2d, v3d) = read_grd("speedy/DATA/init/init.grd")

dataset =  zeros(T, nlon, nlat, nlev, (n3d+n2d))

dataset[:,:,:,1:4] .= v3d

dataset[:,:,1,5:6] .= v2d

write_fortran("test.grd", nlon, nlat, nlev, dataset)

(v2d_new, v3d_new) = read_grd("test.grd")
```
As expected when I compare (v2d, v3d) and  (v2d_new, v3d_new) they are identical.

My problem arises when I want to pass the test.grd (which will actually be called YYYYMMDDHH.grd) file to SPEEDY. 
This is carried out by creating a symlink to the test.grd file in the following bash [script](https://github.com/DanGiles/ParticleDA.jl/blob/dg/speedy/speedy/model/dafcst.sh). This will serve as the initial condition for the SPEEDY model.

`
ln -fs $OUTPUT/anal/$MEM/${YMDH}.grd fort.90
` 

Would it help if I sent you a SPEEDY output file?

**Comment by giordano** [comment]
Note that the function [`read_grd4`](https://github.com/samhatfield/letkf-speedy/blob/fa12565970cb672a0cff85b28cd04beecd856539/common/common_speedy.f90#L197-L225) in Speedy reads single-precision numbers (`Float32` in Julia), here you're using double precision (`Float64`) instead.  That may be a source of problems.  Where is the `read_grd` function defined?  I don't see it anywhere in [your fork](https://github.com/DanGiles/ParticleDA.jl/tree/ccb63ebc8794cc5a695eead3a8dda2e51db70500/speedy/model), I could only find `read_grd!`

> Would it help if I sent you a SPEEDY output file?

Not sure, but it doesn't hurt :slightly_smiling_face:

**Comment by DanGiles** [comment]
Apologies read_grd is defined as follows:

```Julia
function read_grd(filename)

    nlon = 96
    nlat = 48
    nij0 = nlon*nlat
    iolen = 4
    nv3d = 4
    nv2d = 2
    nlev = 8

    v3d = Array{Float32, 4}(undef, nlon, nlat, nlev, nv3d)
    v2d = Array{Float32, 3}(undef, nlon, nlat, nv2d)

    f = FortranFile(filename, access="direct", recl=nij0*iolen, convert="big-endian")

    irec = 1

    for n = 1:nv3d
        for k = 1:nlev
            v3d[:,:,k,n] = read(f, (Float32, nlon, nlat), rec=irec)
            irec += 1
        end
    end

    for n = 1:nv2d
        v2d[:,:,n] = read(f, (Float32, nlon, nlat), rec = irec)
        irec += 1
    end

    close(f)

    return (v2d, v3d)
end
```
In my current write_fortran function, does defining v3d and v2d as the following ensure that we are writing single-precision?

```Julia
v3d = Array{Float32, 4}(undef, nlon, nlat, nlev, nv3d)
v2d = Array{Float32, 3}(undef, nlon, nlat, nv2d)
```
Please find attached a SPEEDY output file
[1982010100.grd.zip](https://github.com/Team-RADDISH/ParticleDA.jl/files/7499583/1982010100.grd.zip)

**Comment by giordano** [comment]
> In my current write_fortran function, does defining v3d and v2d as the following ensure that we are writing single-precision?

Yes, arrays with elements of type `Float32` use single precision, which matches what speedy does to read the files.

For the record, I used this Julia script to write 2 arrays to file:
```julia
using FortranFiles

v3d = randn(Float32, 2, 2, 2, 2)
v2d = randn(Float32, 2, 2, 2)
f = FortranFile("/tmp/foo.dat", "w", access="direct", recl=(4 * 2 * 2))
irec = 1
for i in 1:2
    for j in 1:2 
        write(f, v3d[:,:,j,i]; rec=irec)
        global irec += 1
    end
end
for i in 1:2
    write(f, v2d[:,:,i], rec=irec)
    global irec += 1
end
close(f)
```
and this Fortran program to read back the file from disk (closely based on [how speedy reads files](https://github.com/samhatfield/letkf-speedy/blob/fa12565970cb672a0cff85b28cd04beecd856539/common/common_speedy.f90#L197-L225)):
```fortran
PROGRAM main
  IMPLICIT NONE
  INTEGER,PARAMETER :: r_sngl=kind(0.0e0)
  INTEGER,PARAMETER :: nlon=2,nlat=2,nlev=2,nv2d=2,nv3d=2
  CHARACTER(*),PARAMETER :: filename='/tmp/foo.dat'
  REAL(r_sngl) :: v3d(nlon,nlat,nlev,nv3d)
  REAL(r_sngl) :: v2d(nlon,nlat,nv2d)
  INTEGER :: iunit,iolen
  INTEGER :: i,j,k,n,irec,nij0

  nij0 = nlon * nlat
  iunit=11
  INQUIRE(IOLENGTH=iolen) iolen
  OPEN(iunit,FILE=filename,FORM='unformatted',ACCESS='direct',RECL=nij0*iolen)

  irec=1
  DO n=1,nv3d
    DO k=1,nlev
      READ(iunit,REC=irec) ((v3d(i,j,k,n),i=1,nlon),j=1,nlat)
      irec = irec + 1
    END DO
  END DO

  DO n=1,nv2d
    READ(iunit,REC=irec) ((v2d(i,j,n),i=1,nlon),j=1,nlat)
    irec = irec + 1
  END DO

  CLOSE(iunit)

  WRITE (*,*) v2d
  WRITE (*,*) v3d

END PROGRAM main
```
Output of this program:
```
  0.524990737     -0.189895257     -0.263706386       1.63854229     -0.300967187     -0.311691880       1.31338227      -1.32154751    
   1.14990878     -0.255784541      0.512954772       1.13430202     -0.132320210       1.52468240      0.535124004     -0.408873230      -1.32983112     -0.611415625       8.83856416E-03 -0.359796703     -0.591043890     -0.356946021      0.459834397     -0.321428001    
```
Arrays v3d and v2d written by the Julia script are
```julia
julia> v2d[:]
8-element Vector{Float32}:
  0.52499074
 -0.18989526
 -0.2637064
  1.6385423
 -0.3009672
 -0.31169188
  1.3133823
 -1.3215475

julia> v3d[:]
16-element Vector{Float32}:
  1.1499088
 -0.25578454
  0.5129548
  1.134302
 -0.13232021
  1.5246824
  0.535124
 -0.40887323
 -1.3298311
 -0.6114156
  0.008838564
 -0.3597967
 -0.5910439
 -0.35694602
  0.4598344
 -0.321428
```
As far as I can tell, the data is written and read back correctly.  Note that I'm not using `big-endian` format, unlike what you did in
https://github.com/Team-RADDISH/ParticleDA.jl/blob/ccb63ebc8794cc5a695eead3a8dda2e51db70500/speedy/model/model.jl#L531

Anyways, tomorrow we can discuss off-line to better understand what is not working for you.

**Comment by giordano** [comment]
Also, as a side note, the above Julia script to write data to file can be greatly simplified without using `FortranFiles.jl`:
```julia
v3d = randn(Float32, 2, 2, 2, 2)
v2d = randn(Float32, 2, 2, 2)
open("/tmp/foo.dat", "w") do io
    write(io, v3d)
    write(io, v2d)
end
```

**Comment by DanGiles** [comment]
As discussed in yesterday's meeting I am having some difficulty with implementing periodic covariance functions within the GaussianRandomFields package. My first draft of a code for generating the covariance matrix based on the geodesic distance is given here:

```Julia
using LinearAlgebra, Statistics, Plots

function SphericalAngle(x::Tuple{Float64, Float64}, y::Tuple{Float64, Float64}) where d
    @inbounds λ₁, φ₁ = x
    @inbounds λ₂, φ₂ = y
    Δλ = λ₂ - λ₁  # longitude
    Δφ = φ₂ - φ₁  # latitude
    # haversine formula
    a = sin(Δφ/2)^2 + cos(φ₁)*cos(φ₂)*sin(Δλ/2)^2
    # distance 
    a = 2 * ( asin( min(√a, one(a)) ))
    return a
end

function apply_spherical_periodic!(C::Matrix, x::NTuple{d,AbstractVector},
                                        y::NTuple{d,AbstractVector}) where d
    xiterator = enumerate(Iterators.product(x...))
    for (j, idy) in enumerate(Iterators.product(y...))
        for (i, idx) in Iterators.take(xiterator, j)
            z = SphericalAngle(idx, idy)
            @inbounds C[i, j] = squared_exponential(λ, z)
        end
    end
    Symmetric(C, :U)
end

function squared_exponential(λ::Real, z::Real)
    cov = exp(-(z/ λ)^2)
    return cov
end

# Setting up the coordinates 
x = LinRange(0,360,96)
y = LinRange(0,180,48)
# Empty Covariance Matrix
C = zeros( prod(length, (x,y)), prod(length, (x,y)))
λ = 0.5 # correlation length λ of squared exponential covariance

C .= apply_spherical_periodic!(C, (x,y), (x,y))
# Plot
heatmap(C)

```

What is the best way to incorporate this covariance matrix with the GaussianRandomFields generators?

@matt-graham: If you have any other suggestions with regards to the sample code above please let me know. 

Thanks

**Comment by matt-graham** [comment]
Hi @DanGiles. I've found an approach that *sort of* works. The idea is to write custom methods for the [`apply_symmetric!`](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/blob/5d9257cb452e2b91387e206a1d074da63a81156f/src/covariance_functions/covariance_functions.jl#L142) and [`apply_non_symmetric!`](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/blob/5d9257cb452e2b91387e206a1d074da63a81156f/src/covariance_functions/covariance_functions.jl#L155) functions which are used by `GaussianRandomFields` to construct the covariance matrix explicitly (which makes this applicable to I think the `Cholesky`, `Spectral` and `KarhunenLoeve` generators but not the `CirculantEmbedding`). We can replace the calculation of the difference between the two points with a call to a custom distance function which I define via a wrapper structure `CustomDistanceCovarianceStructure` which contains of an existing covariance structure plus singleton defining the distance function to use (@giordano might be able to advise on a better way of structuring this)

```Julia
using Statistics
using GaussianRandomFields
import GaussianRandomFields: shortname, apply, apply_symmetric!, apply_non_symmetric!

abstract type Distance end

shortname(::Distance) = "custom distance"
function apply(::Distance, x::NTuple{d, Real}, y::NTuple{d, Real}) end

struct CustomDistanceCovarianceStructure{T} <: CovarianceStructure{T} 
    distance::Distance
    cov::IsotropicCovarianceStructure{T}
end

apply(s::CustomDistanceCovarianceStructure, ρ::Real) = apply(s.cov, ρ)

shortname(s::CustomDistanceCovarianceStructure) = shortname(s.cov) * " on " * shortname(s.distance)

Statistics.std(c::IsotropicCovarianceStructure) = c.σ
Statistics.std(s::CustomDistanceCovarianceStructure) = Statistics.std(s.cov)
Statistics.std(f::AbstractCovarianceFunction) = Statistics.std(f.cov)

function apply_symmetric!(
    C::Matrix,
    s::CustomDistanceCovarianceStructure,
    x::NTuple{d, AbstractVector},
    y::NTuple{d, AbstractVector}
) where d
    xiterator = enumerate(Iterators.product(x...))
    for (j, idy) in enumerate(Iterators.product(y...))
        for (i, idx) in Iterators.take(xiterator, j)
            @inbounds C[i, j] = apply(s.cov, apply(s.distance, idx, idy))
        end
    end
    Symmetric(C, :U)
end

function apply_non_symmetric!(
    C::Matrix,
    s::CustomDistanceCovarianceStructure,
    x::NTuple{d, AbstractVector},
    y::NTuple{d, AbstractVector}
) where d
    xiterator = enumerate(Iterators.product(x...))
    for (j, idy) in enumerate(Iterators.product(y...))
        for (i, idx) in xiterator
            @inbounds C[i, j] = apply(s.cov, apply(s.distance, idx, idy))
        end
    end
    C
end
```
we can then adapt your definition of the spherical distance function as follows

```Julia
struct SphericalDistance <: Distance end

shortname(::SphericalDistance) = "spherical distance"

function apply(::SphericalDistance, x::Tuple{Float64, Float64}, y::Tuple{Float64, Float64})
    @inbounds λ₁, φ₁ = x
    @inbounds λ₂, φ₂ = y
    Δλ = λ₂ - λ₁  # longitude difference
    Δφ = φ₂ - φ₁  # latitude difference
    # haversine formula
    a = sin(Δφ/2)^2 + cos(φ₁)*cos(φ₂)*sin(Δλ/2)^2
    # distance
    2 * ( asin( min(√a, one(a)) ))
end
```

For comparison we could also define a Euclidean distance corresponding to the existing default in the package as

```Julia
struct EuclideanDistance <: Distance end
shortname(::EuclideanDistance) = "Euclidean distance"
apply(::EuclideanDistance, x::NTuple{d, Real}, y::NTuple{d, Real}) where d = norm(x .- y)
```

We can then construct a covariance function plus Gaussian random field using this distance function plus an isotropic covariance structure (using squared exponential here for consistency with your example) as follows

```Julia
# Setting up the coordinates
longitudes = range(0, 2π, 48)
latitudes = range(0, π, 48)
λ = 1. # correlation length λ of squared exponential covariance
cov = CovarianceFunction(
    2, 
    CustomDistanceCovarianceStructure(
        SphericalDistance(), 
        SquaredExponential(λ)
    )
)
grf = GaussianRandomField(cov, Spectral(), longitudes, latitudes)
```
The definition you used for the spherical distance assumes the latitude and longitude are in radians rather than degrees so I adjusted the ranges compared to what you had. Also there seems to be a bug in the plotting code in `GaussianRandomFields` that means it doesn't plot fields with differing number of points along the two dimensions correctly hence I've made the resolution in the latitude and longitude directions equal here (this also seems to apply when using the inbuilt covariance structures rather than being specific to our adaptation here).

While we can generate samples from the resulting `GaussianRandomField` object, for example

![image](https://user-images.githubusercontent.com/6746980/145269446-5c1b2f31-82ac-4a83-a120-f16d4f28cba6.png)

there are a few issues:

  * The `CirculantEmbedding` generator doesn't use `apply_symmetric!` / `apply_non_symmetric!` but instead uses a lower-level `apply` method, so this doesn't work for that case. I'm also not sure the circulant embedding method is applicable for this case to start with as I think it assumes a stationary covariance function (which I don't think is the case with the spherical distance function)
  * The resulting covariance matrices seem to generally be non-positive definite (the package warns there are small negative eigenvalues though I think this could be a numerical artefact and that the matrices are instead just semi-definite), even when using a covariance structure which gives a positive definite covariance matrix with the Euclidean distance. This means the `Cholesky` generator doesn't work and the `KarhunenLoeve` generator fails if you select a number of basis functions which exceed the number of positive eigenvalues.
  * The sampled fields when plotted appear to be periodic along the latitude axis rather than longitude axis though I think this could be related to the bug causing the incorrect plot output with non-square grids.

**Comment by matt-graham** [comment]
> The sampled fields when plotted appear to be periodic along the latitude axis rather than longitude axis though I think this could be related to the bug causing the incorrect plot output with non-square grids.

I have confirmed that the bug in the `GaussianRandomField` plotting code for non-square grids is the reason for this discrepancy (basically the transpose of the sampled field seems to be getting plotted), so I think the fields are being generated with the periodicity along the correct axis. I've raised an issue about this (PieterjanRobbe/GaussianRandomFields.jl/issues/41).
